name: weathers_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.0
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/
